In [1]:
import numpy as np

In [2]:
arr = np.array([[4,5,6,111],[4,5,89,6]] , np.int64)

In [3]:
arr[0,3]

111

In [4]:
arr.shape

(2, 4)

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr[0,3]

111

In [7]:
arr[0,3] = 222
arr

array([[  4,   5,   6, 222],
       [  4,   5,  89,   6]], dtype=int64)

array creation

In [8]:
listarray = np.array([[2,5,6],[4,5,7],[5,8,2]])
listarray

array([[2, 5, 6],
       [4, 5, 7],
       [5, 8, 2]])

In [9]:
listarray.dtype

dtype('int32')

In [10]:
listarray.shape

(3, 3)

In [11]:
listarray.size

9

zeros

In [12]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [13]:
zeros = np.zeros((2,6))
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

range

In [14]:
rng = np.arange(10)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

linspace

In [15]:
lspace = np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

empty

In [16]:
emp = np.empty((4,5))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.33772792e-307, 6.23047503e-307],
       [1.33512512e-306, 8.90095411e-307, 1.33511018e-306,
        1.33511969e-306, 3.11525958e-307],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 1.29062229e-306],
       [9.79094971e-307, 6.89804133e-307, 1.20160711e-306,
        9.79101761e-307, 2.22522596e-306]])

In [17]:
emp_like = np.empty_like(rng)
emp_like

array([      0,       1,       0, 5570652,    1076,       0,     768,
             0, 5636175,      79])

identity matrix

In [18]:
ide = np.identity(4)
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
ide.shape

(4, 4)

In [20]:
ide.size

16

In [21]:
ar = np.arange(99)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [22]:
ar = ar.reshape(3,33)
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [23]:
ar.shape

(3, 33)

In [24]:
ar = ar.ravel()
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
ar.shape

(99,)

axis

In [26]:
x = [[2,5,6],[4,8,9],[4,5,3]]
arr = np.array(x)
arr

array([[2, 5, 6],
       [4, 8, 9],
       [4, 5, 3]])

In [27]:
arr.sum(axis = 0)
# axix = 0 means rows

array([10, 18, 18])

In [28]:
arr.sum(axis = 1)
# axis = 1 means colums

array([13, 21, 12])

In [29]:
arr.T
# T means transpose

array([[2, 4, 4],
       [5, 8, 5],
       [6, 9, 3]])

In [30]:
arr

array([[2, 5, 6],
       [4, 8, 9],
       [4, 5, 3]])

In [31]:
arr.flat

In [32]:
for item in arr.flat:
    print(item)

2
5
6
4
8
9
4
5
3


In [33]:
arr.ndim
# how many dimentions in array

2

In [34]:
arr.size

9

In [35]:
arr.nbytes

36

make a one dimention array

In [36]:
one = np.array([5,6,7,82,9,2,1])
one

array([ 5,  6,  7, 82,  9,  2,  1])

In [37]:
one.argmax()

3

In [38]:
one.max()

82

In [39]:
one.argmin()

6

In [40]:
one.min()

1

In [41]:
one.argsort()
# these are the index no. of sort array

array([6, 5, 0, 1, 2, 4, 3], dtype=int64)

In [42]:
one.sort()
one

array([ 1,  2,  5,  6,  7,  9, 82])

In [43]:
arr

array([[2, 5, 6],
       [4, 8, 9],
       [4, 5, 3]])

In [44]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [45]:
arr.argmax()

5

In [46]:
arr.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [47]:
arr.argmax(axis=1)

array([2, 2, 1], dtype=int64)

In [48]:
arr.argmin()

0

In [49]:
arr.argmin(axis=0)

array([0, 0, 2], dtype=int64)

In [50]:
arr.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [51]:
arr.ravel()

array([2, 5, 6, 4, 8, 9, 4, 5, 3])

In [52]:
arr.reshape(9,1)

array([[2],
       [5],
       [6],
       [4],
       [8],
       [9],
       [4],
       [5],
       [3]])

In [53]:
arr.reshape(9,)

array([2, 5, 6, 4, 8, 9, 4, 5, 3])

In [54]:
arr

array([[2, 5, 6],
       [4, 8, 9],
       [4, 5, 3]])

In [55]:
arr1 = np.array([[2,5,3],[8,9,4],[5,8,3]])
arr1

array([[2, 5, 3],
       [8, 9, 4],
       [5, 8, 3]])

In [57]:
arr + arr1
# list can't add two matrix but numpy can

array([[ 4, 10,  9],
       [12, 17, 13],
       [ 9, 13,  6]])

In [59]:
arr * arr1

array([[ 4, 25, 18],
       [32, 72, 36],
       [20, 40,  9]])

In [65]:
np.sqrt(arr)

array([[1.41421356, 2.23606798, 2.44948974],
       [2.        , 2.82842712, 3.        ],
       [2.        , 2.23606798, 1.73205081]])

In [67]:
np.min(arr)

2

In [73]:
arr.min()

2

In [70]:
np.max(arr)

9

In [74]:
arr.max()

9

In [76]:
arr.sum()

46

In [78]:
np.sum(arr)

46

In [80]:
arr

array([[2, 5, 6],
       [4, 8, 9],
       [4, 5, 3]])

In [81]:
np.where(arr > 6)

(array([1, 1], dtype=int64), array([1, 2], dtype=int64))

In [83]:
type(np.where(arr > 6))

tuple

In [84]:
np.count_nonzero(arr)

9